### ISSUE TITLE
[Question] Context of "FIXME" comment in HLSL implementation

### ISSUE THREAD

**Issue by simco50** [jdupuy/libleb#1]
Hi,

I've been implementing the CBT + LEB algorithm on the GPU in HLSL based off the CBT paper building it up from scratch without using the libleb or libcbt libraries to gain some of its intuition.
I've been scratching my head over an issue where a node may not always merge back correctly.
I've put in a hack to resolve that on my end and I just realized that the HLSL implementation in this repository has the exact same hack.
https://github.com/jdupuy/libleb/blob/584d4a709060e49b30789c9ff907237ce252e2ba/hlsl/LongestEdgeBisection.hlsl#L207-L211
I see that only the HLSL implementation has this hack and the C and GLSL versions do not. However, I have the identical issue in my C++ implementation as well.
I haven't found out why exactly it is going wrong, I wonder if you have gained any insight in this?

Thanks!
Simon

**Comment by jdupuy** [comment]
Hi Simon, 

Regarding the current HLSL workaround: I wrote the HLSL version for the Unity game engine and had to add the FIXME line to get the nodes to merge properly as they were behaving exactly the way you describe. I haven't looked into this at all since.
 
Regarding your C++ implementation: you should be able to get it to run without any hacks. I encourage you to use my C code as reference. 

Best,
J

**Comment by simco50** [comment]
Thanks for getting back.
I believe I found that this issue happens when not alternating between splitting and merging and instead doing both in the same pass.
As an experiment, I replaced "FLAG_SPLIT" and "FLAG_MERGE" with "1" in your [LEB/CBT demo shader](https://github.com/jdupuy/LongestEdgeBisection2D/blob/6e0f6e5a6e66092b354adee7ae4b60a9c4853e62/subdivision/shaders/subdivision.glsl#L52) and I can reproduce the problem.
Alternating splitting/merging as you did in your demo repository allows me to remove this hack without further artifacts both in my C++ and HLSL implementation.
